version: "3.1"
services:
  app-gui:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"
    container_name: da_gui
  app-persistierung:
    build: ./app_persistierung
    container_name: da_persistierung
    depends_on:
      - db
    ports:
      - "5005:5005"
  db:
    image: mysql
    container_name: da_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: da_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "5001:80"
    depends_on:
      - db
