# Use an official Python runtime as an image
FROM python:3.6

# The EXPOSE instruction indicates the ports on which a container
EXPOSE 5005

# Sets the working directory for following COPY and CMD instructions
# Notice we haven’t created a directory by this name - this instruction
# creates a directory with this name if it doesn’t exist
WORKDIR /app_persistierung

COPY requirements.txt /app_persistierung
RUN python -m pip install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt



# Run app.py when the container launches
COPY da-persistierung-app.py /app_persistierung
COPY /classes classes/
COPY /config config/

CMD python da-persistierung-app.py

